// AUTO-GENERATED by scripts/gen-countries.cjs — do not edit by hand.
export interface Country { iso: string; name: string; nameEn: string; calling: string }
export const DEFAULT_COUNTRY = "SA";
export const COUNTRIES: Country[] = [
  {
    "iso": "SA",
    "name": "المملكة العربية السعودية",
    "nameEn": "Saudi Arabia",
    "calling": "966"
  },
  {
    "iso": "IS",
    "name": "آيسلندا",
    "nameEn": "Iceland",
    "calling": "354"
  },
  {
    "iso": "ET",
    "name": "إثيوبيا",
    "nameEn": "Ethiopia",
    "calling": "251"
  },
  {
    "iso": "AZ",
    "name": "أذربيجان",
    "nameEn": "Azerbaijan",
    "calling": "994"
  },
  {
    "iso": "AM",
    "name": "أرمينيا",
    "nameEn": "Armenia",
    "calling": "374"
  },
  {
    "iso": "AW",
    "name": "أروبا",
    "nameEn": "Aruba",
    "calling": "297"
  },
  {
    "iso": "ER",
    "name": "إريتريا",
    "nameEn": "Eritrea",
    "calling": "291"
  },
  {
    "iso": "ES",
    "name": "إسبانيا",
    "nameEn": "Spain",
    "calling": "34"
  },
  {
    "iso": "AU",
    "name": "أستراليا",
    "nameEn": "Australia",
    "calling": "61"
  },
  {
    "iso": "EE",
    "name": "إستونيا",
    "nameEn": "Estonia",
    "calling": "372"
  },
  {
    "iso": "IL",
    "name": "إسرائيل",
    "nameEn": "Israel",
    "calling": "972"
  },
  {
    "iso": "SZ",
    "name": "إسواتيني",
    "nameEn": "Eswatini",
    "calling": "268"
  },
  {
    "iso": "AF",
    "name": "أفغانستان",
    "nameEn": "Afghanistan",
    "calling": "93"
  },
  {
    "iso": "PS",
    "name": "الأراضي الفلسطينية",
    "nameEn": "Palestinian Territories",
    "calling": "970"
  },
  {
    "iso": "AR",
    "name": "الأرجنتين",
    "nameEn": "Argentina",
    "calling": "54"
  },
  {
    "iso": "JO",
    "name": "الأردن",
    "nameEn": "Jordan",
    "calling": "962"
  },
  {
    "iso": "IO",
    "name": "الإقليم البريطاني في المحيط الهندي",
    "nameEn": "British Indian Ocean Territory",
    "calling": "246"
  },
  {
    "iso": "EC",
    "name": "الإكوادور",
    "nameEn": "Ecuador",
    "calling": "593"
  },
  {
    "iso": "AE",
    "name": "الإمارات العربية المتحدة",
    "nameEn": "United Arab Emirates",
    "calling": "971"
  },
  {
    "iso": "AL",
    "name": "ألبانيا",
    "nameEn": "Albania",
    "calling": "355"
  },
  {
    "iso": "BH",
    "name": "البحرين",
    "nameEn": "Bahrain",
    "calling": "973"
  },
  {
    "iso": "BR",
    "name": "البرازيل",
    "nameEn": "Brazil",
    "calling": "55"
  },
  {
    "iso": "PT",
    "name": "البرتغال",
    "nameEn": "Portugal",
    "calling": "351"
  },
  {
    "iso": "BA",
    "name": "البوسنة والهرسك",
    "nameEn": "Bosnia & Herzegovina",
    "calling": "387"
  },
  {
    "iso": "CZ",
    "name": "التشيك",
    "nameEn": "Czechia",
    "calling": "420"
  },
  {
    "iso": "ME",
    "name": "الجبل الأسود",
    "nameEn": "Montenegro",
    "calling": "382"
  },
  {
    "iso": "DZ",
    "name": "الجزائر",
    "nameEn": "Algeria",
    "calling": "213"
  },
  {
    "iso": "DK",
    "name": "الدانمرك",
    "nameEn": "Denmark",
    "calling": "45"
  },
  {
    "iso": "CV",
    "name": "الرأس الأخضر",
    "nameEn": "Cape Verde",
    "calling": "238"
  },
  {
    "iso": "SV",
    "name": "السلفادور",
    "nameEn": "El Salvador",
    "calling": "503"
  },
  {
    "iso": "SN",
    "name": "السنغال",
    "nameEn": "Senegal",
    "calling": "221"
  },
  {
    "iso": "SD",
    "name": "السودان",
    "nameEn": "Sudan",
    "calling": "249"
  },
  {
    "iso": "SE",
    "name": "السويد",
    "nameEn": "Sweden",
    "calling": "46"
  },
  {
    "iso": "EH",
    "name": "الصحراء الغربية",
    "nameEn": "Western Sahara",
    "calling": "212"
  },
  {
    "iso": "SO",
    "name": "الصومال",
    "nameEn": "Somalia",
    "calling": "252"
  },
  {
    "iso": "CN",
    "name": "الصين",
    "nameEn": "China",
    "calling": "86"
  },
  {
    "iso": "IQ",
    "name": "العراق",
    "nameEn": "Iraq",
    "calling": "964"
  },
  {
    "iso": "GA",
    "name": "الغابون",
    "nameEn": "Gabon",
    "calling": "241"
  },
  {
    "iso": "VA",
    "name": "الفاتيكان",
    "nameEn": "Vatican City",
    "calling": "39"
  },
  {
    "iso": "PH",
    "name": "الفلبين",
    "nameEn": "Philippines",
    "calling": "63"
  },
  {
    "iso": "CM",
    "name": "الكاميرون",
    "nameEn": "Cameroon",
    "calling": "237"
  },
  {
    "iso": "CG",
    "name": "الكونغو - برازافيل",
    "nameEn": "Congo - Brazzaville",
    "calling": "242"
  },
  {
    "iso": "CD",
    "name": "الكونغو - كينشاسا",
    "nameEn": "Congo - Kinshasa",
    "calling": "243"
  },
  {
    "iso": "KW",
    "name": "الكويت",
    "nameEn": "Kuwait",
    "calling": "965"
  },
  {
    "iso": "DE",
    "name": "ألمانيا",
    "nameEn": "Germany",
    "calling": "49"
  },
  {
    "iso": "MA",
    "name": "المغرب",
    "nameEn": "Morocco",
    "calling": "212"
  },
  {
    "iso": "MX",
    "name": "المكسيك",
    "nameEn": "Mexico",
    "calling": "52"
  },
  {
    "iso": "GB",
    "name": "المملكة المتحدة",
    "nameEn": "United Kingdom",
    "calling": "44"
  },
  {
    "iso": "NO",
    "name": "النرويج",
    "nameEn": "Norway",
    "calling": "47"
  },
  {
    "iso": "AT",
    "name": "النمسا",
    "nameEn": "Austria",
    "calling": "43"
  },
  {
    "iso": "NE",
    "name": "النيجر",
    "nameEn": "Niger",
    "calling": "227"
  },
  {
    "iso": "IN",
    "name": "الهند",
    "nameEn": "India",
    "calling": "91"
  },
  {
    "iso": "US",
    "name": "الولايات المتحدة",
    "nameEn": "United States",
    "calling": "1"
  },
  {
    "iso": "JP",
    "name": "اليابان",
    "nameEn": "Japan",
    "calling": "81"
  },
  {
    "iso": "YE",
    "name": "اليمن",
    "nameEn": "Yemen",
    "calling": "967"
  },
  {
    "iso": "GR",
    "name": "اليونان",
    "nameEn": "Greece",
    "calling": "30"
  },
  {
    "iso": "AG",
    "name": "أنتيغوا وبربودا",
    "nameEn": "Antigua & Barbuda",
    "calling": "1"
  },
  {
    "iso": "AD",
    "name": "أندورا",
    "nameEn": "Andorra",
    "calling": "376"
  },
  {
    "iso": "ID",
    "name": "إندونيسيا",
    "nameEn": "Indonesia",
    "calling": "62"
  },
  {
    "iso": "AO",
    "name": "أنغولا",
    "nameEn": "Angola",
    "calling": "244"
  },
  {
    "iso": "AI",
    "name": "أنغويلا",
    "nameEn": "Anguilla",
    "calling": "1"
  },
  {
    "iso": "UY",
    "name": "أورغواي",
    "nameEn": "Uruguay",
    "calling": "598"
  },
  {
    "iso": "UZ",
    "name": "أوزبكستان",
    "nameEn": "Uzbekistan",
    "calling": "998"
  },
  {
    "iso": "UG",
    "name": "أوغندا",
    "nameEn": "Uganda",
    "calling": "256"
  },
  {
    "iso": "UA",
    "name": "أوكرانيا",
    "nameEn": "Ukraine",
    "calling": "380"
  },
  {
    "iso": "IR",
    "name": "إيران",
    "nameEn": "Iran",
    "calling": "98"
  },
  {
    "iso": "IE",
    "name": "أيرلندا",
    "nameEn": "Ireland",
    "calling": "353"
  },
  {
    "iso": "IT",
    "name": "إيطاليا",
    "nameEn": "Italy",
    "calling": "39"
  },
  {
    "iso": "PG",
    "name": "بابوا غينيا الجديدة",
    "nameEn": "Papua New Guinea",
    "calling": "675"
  },
  {
    "iso": "PY",
    "name": "باراغواي",
    "nameEn": "Paraguay",
    "calling": "595"
  },
  {
    "iso": "PK",
    "name": "باكستان",
    "nameEn": "Pakistan",
    "calling": "92"
  },
  {
    "iso": "PW",
    "name": "بالاو",
    "nameEn": "Palau",
    "calling": "680"
  },
  {
    "iso": "BB",
    "name": "بربادوس",
    "nameEn": "Barbados",
    "calling": "1"
  },
  {
    "iso": "BM",
    "name": "برمودا",
    "nameEn": "Bermuda",
    "calling": "1"
  },
  {
    "iso": "BN",
    "name": "بروناي",
    "nameEn": "Brunei",
    "calling": "673"
  },
  {
    "iso": "BE",
    "name": "بلجيكا",
    "nameEn": "Belgium",
    "calling": "32"
  },
  {
    "iso": "BG",
    "name": "بلغاريا",
    "nameEn": "Bulgaria",
    "calling": "359"
  },
  {
    "iso": "BZ",
    "name": "بليز",
    "nameEn": "Belize",
    "calling": "501"
  },
  {
    "iso": "BD",
    "name": "بنغلاديش",
    "nameEn": "Bangladesh",
    "calling": "880"
  },
  {
    "iso": "PA",
    "name": "بنما",
    "nameEn": "Panama",
    "calling": "507"
  },
  {
    "iso": "BJ",
    "name": "بنين",
    "nameEn": "Benin",
    "calling": "229"
  },
  {
    "iso": "BT",
    "name": "بوتان",
    "nameEn": "Bhutan",
    "calling": "975"
  },
  {
    "iso": "BW",
    "name": "بوتسوانا",
    "nameEn": "Botswana",
    "calling": "267"
  },
  {
    "iso": "PR",
    "name": "بورتوريكو",
    "nameEn": "Puerto Rico",
    "calling": "1"
  },
  {
    "iso": "BF",
    "name": "بوركينا فاسو",
    "nameEn": "Burkina Faso",
    "calling": "226"
  },
  {
    "iso": "BI",
    "name": "بوروندي",
    "nameEn": "Burundi",
    "calling": "257"
  },
  {
    "iso": "PL",
    "name": "بولندا",
    "nameEn": "Poland",
    "calling": "48"
  },
  {
    "iso": "BO",
    "name": "بوليفيا",
    "nameEn": "Bolivia",
    "calling": "591"
  },
  {
    "iso": "PF",
    "name": "بولينيزيا الفرنسية",
    "nameEn": "French Polynesia",
    "calling": "689"
  },
  {
    "iso": "PE",
    "name": "بيرو",
    "nameEn": "Peru",
    "calling": "51"
  },
  {
    "iso": "BY",
    "name": "بيلاروس",
    "nameEn": "Belarus",
    "calling": "375"
  },
  {
    "iso": "TH",
    "name": "تايلاند",
    "nameEn": "Thailand",
    "calling": "66"
  },
  {
    "iso": "TW",
    "name": "تايوان",
    "nameEn": "Taiwan",
    "calling": "886"
  },
  {
    "iso": "TM",
    "name": "تركمانستان",
    "nameEn": "Turkmenistan",
    "calling": "993"
  },
  {
    "iso": "TR",
    "name": "تركيا",
    "nameEn": "Türkiye",
    "calling": "90"
  },
  {
    "iso": "TA",
    "name": "تريستان دا كونا",
    "nameEn": "Tristan da Cunha",
    "calling": "290"
  },
  {
    "iso": "TT",
    "name": "ترينيداد وتوباغو",
    "nameEn": "Trinidad & Tobago",
    "calling": "1"
  },
  {
    "iso": "TD",
    "name": "تشاد",
    "nameEn": "Chad",
    "calling": "235"
  },
  {
    "iso": "CL",
    "name": "تشيلي",
    "nameEn": "Chile",
    "calling": "56"
  },
  {
    "iso": "TZ",
    "name": "تنزانيا",
    "nameEn": "Tanzania",
    "calling": "255"
  },
  {
    "iso": "TG",
    "name": "توغو",
    "nameEn": "Togo",
    "calling": "228"
  },
  {
    "iso": "TV",
    "name": "توفالو",
    "nameEn": "Tuvalu",
    "calling": "688"
  },
  {
    "iso": "TK",
    "name": "توكيلاو",
    "nameEn": "Tokelau",
    "calling": "690"
  },
  {
    "iso": "TN",
    "name": "تونس",
    "nameEn": "Tunisia",
    "calling": "216"
  },
  {
    "iso": "TO",
    "name": "تونغا",
    "nameEn": "Tonga",
    "calling": "676"
  },
  {
    "iso": "TL",
    "name": "تيمور - ليشتي",
    "nameEn": "Timor-Leste",
    "calling": "670"
  },
  {
    "iso": "JM",
    "name": "جامايكا",
    "nameEn": "Jamaica",
    "calling": "1"
  },
  {
    "iso": "GI",
    "name": "جبل طارق",
    "nameEn": "Gibraltar",
    "calling": "350"
  },
  {
    "iso": "AX",
    "name": "جزر آلاند",
    "nameEn": "Åland Islands",
    "calling": "358"
  },
  {
    "iso": "BS",
    "name": "جزر البهاما",
    "nameEn": "Bahamas",
    "calling": "1"
  },
  {
    "iso": "KM",
    "name": "جزر القمر",
    "nameEn": "Comoros",
    "calling": "269"
  },
  {
    "iso": "MQ",
    "name": "جزر المارتينيك",
    "nameEn": "Martinique",
    "calling": "596"
  },
  {
    "iso": "MV",
    "name": "جزر المالديف",
    "nameEn": "Maldives",
    "calling": "960"
  },
  {
    "iso": "TC",
    "name": "جزر توركس وكايكوس",
    "nameEn": "Turks & Caicos Islands",
    "calling": "1"
  },
  {
    "iso": "SB",
    "name": "جزر سليمان",
    "nameEn": "Solomon Islands",
    "calling": "677"
  },
  {
    "iso": "FO",
    "name": "جزر فارو",
    "nameEn": "Faroe Islands",
    "calling": "298"
  },
  {
    "iso": "FK",
    "name": "جزر فوكلاند",
    "nameEn": "Falkland Islands",
    "calling": "500"
  },
  {
    "iso": "VI",
    "name": "جزر فيرجن الأمريكية",
    "nameEn": "U.S. Virgin Islands",
    "calling": "1"
  },
  {
    "iso": "VG",
    "name": "جزر فيرجن البريطانية",
    "nameEn": "British Virgin Islands",
    "calling": "1"
  },
  {
    "iso": "KY",
    "name": "جزر كايمان",
    "nameEn": "Cayman Islands",
    "calling": "1"
  },
  {
    "iso": "CK",
    "name": "جزر كوك",
    "nameEn": "Cook Islands",
    "calling": "682"
  },
  {
    "iso": "CC",
    "name": "جزر كوكوس (كيلينغ)",
    "nameEn": "Cocos (Keeling) Islands",
    "calling": "61"
  },
  {
    "iso": "MH",
    "name": "جزر مارشال",
    "nameEn": "Marshall Islands",
    "calling": "692"
  },
  {
    "iso": "MP",
    "name": "جزر ماريانا الشمالية",
    "nameEn": "Northern Mariana Islands",
    "calling": "1"
  },
  {
    "iso": "WF",
    "name": "جزر والس وفوتونا",
    "nameEn": "Wallis & Futuna",
    "calling": "681"
  },
  {
    "iso": "AC",
    "name": "جزيرة أسينشيون",
    "nameEn": "Ascension Island",
    "calling": "247"
  },
  {
    "iso": "CX",
    "name": "جزيرة كريسماس",
    "nameEn": "Christmas Island",
    "calling": "61"
  },
  {
    "iso": "IM",
    "name": "جزيرة مان",
    "nameEn": "Isle of Man",
    "calling": "44"
  },
  {
    "iso": "NF",
    "name": "جزيرة نورفولك",
    "nameEn": "Norfolk Island",
    "calling": "672"
  },
  {
    "iso": "CF",
    "name": "جمهورية أفريقيا الوسطى",
    "nameEn": "Central African Republic",
    "calling": "236"
  },
  {
    "iso": "DO",
    "name": "جمهورية الدومينيكان",
    "nameEn": "Dominican Republic",
    "calling": "1"
  },
  {
    "iso": "ZA",
    "name": "جنوب أفريقيا",
    "nameEn": "South Africa",
    "calling": "27"
  },
  {
    "iso": "SS",
    "name": "جنوب السودان",
    "nameEn": "South Sudan",
    "calling": "211"
  },
  {
    "iso": "GE",
    "name": "جورجيا",
    "nameEn": "Georgia",
    "calling": "995"
  },
  {
    "iso": "DJ",
    "name": "جيبوتي",
    "nameEn": "Djibouti",
    "calling": "253"
  },
  {
    "iso": "JE",
    "name": "جيرسي",
    "nameEn": "Jersey",
    "calling": "44"
  },
  {
    "iso": "DM",
    "name": "دومينيكا",
    "nameEn": "Dominica",
    "calling": "1"
  },
  {
    "iso": "RW",
    "name": "رواندا",
    "nameEn": "Rwanda",
    "calling": "250"
  },
  {
    "iso": "RU",
    "name": "روسيا",
    "nameEn": "Russia",
    "calling": "7"
  },
  {
    "iso": "RO",
    "name": "رومانيا",
    "nameEn": "Romania",
    "calling": "40"
  },
  {
    "iso": "RE",
    "name": "روينيون",
    "nameEn": "Réunion",
    "calling": "262"
  },
  {
    "iso": "ZM",
    "name": "زامبيا",
    "nameEn": "Zambia",
    "calling": "260"
  },
  {
    "iso": "ZW",
    "name": "زيمبابوي",
    "nameEn": "Zimbabwe",
    "calling": "263"
  },
  {
    "iso": "CI",
    "name": "ساحل العاج",
    "nameEn": "Côte d’Ivoire",
    "calling": "225"
  },
  {
    "iso": "WS",
    "name": "ساموا",
    "nameEn": "Samoa",
    "calling": "685"
  },
  {
    "iso": "AS",
    "name": "ساموا الأمريكية",
    "nameEn": "American Samoa",
    "calling": "1"
  },
  {
    "iso": "BL",
    "name": "سان بارتليمي",
    "nameEn": "St. Barthélemy",
    "calling": "590"
  },
  {
    "iso": "PM",
    "name": "سان بيير ومكويلون",
    "nameEn": "St. Pierre & Miquelon",
    "calling": "508"
  },
  {
    "iso": "MF",
    "name": "سان مارتن",
    "nameEn": "St. Martin",
    "calling": "590"
  },
  {
    "iso": "SM",
    "name": "سان مارينو",
    "nameEn": "San Marino",
    "calling": "378"
  },
  {
    "iso": "VC",
    "name": "سانت فنسنت وجزر غرينادين",
    "nameEn": "St. Vincent & Grenadines",
    "calling": "1"
  },
  {
    "iso": "KN",
    "name": "سانت كيتس ونيفيس",
    "nameEn": "St. Kitts & Nevis",
    "calling": "1"
  },
  {
    "iso": "LC",
    "name": "سانت لوسيا",
    "nameEn": "St. Lucia",
    "calling": "1"
  },
  {
    "iso": "SX",
    "name": "سانت مارتن",
    "nameEn": "Sint Maarten",
    "calling": "1"
  },
  {
    "iso": "SH",
    "name": "سانت هيلينا",
    "nameEn": "St. Helena",
    "calling": "290"
  },
  {
    "iso": "ST",
    "name": "ساو تومي وبرينسيبي",
    "nameEn": "São Tomé & Príncipe",
    "calling": "239"
  },
  {
    "iso": "LK",
    "name": "سريلانكا",
    "nameEn": "Sri Lanka",
    "calling": "94"
  },
  {
    "iso": "SJ",
    "name": "سفالبارد وجان ماين",
    "nameEn": "Svalbard & Jan Mayen",
    "calling": "47"
  },
  {
    "iso": "SK",
    "name": "سلوفاكيا",
    "nameEn": "Slovakia",
    "calling": "421"
  },
  {
    "iso": "SI",
    "name": "سلوفينيا",
    "nameEn": "Slovenia",
    "calling": "386"
  },
  {
    "iso": "SG",
    "name": "سنغافورة",
    "nameEn": "Singapore",
    "calling": "65"
  },
  {
    "iso": "SY",
    "name": "سوريا",
    "nameEn": "Syria",
    "calling": "963"
  },
  {
    "iso": "SR",
    "name": "سورينام",
    "nameEn": "Suriname",
    "calling": "597"
  },
  {
    "iso": "CH",
    "name": "سويسرا",
    "nameEn": "Switzerland",
    "calling": "41"
  },
  {
    "iso": "SL",
    "name": "سيراليون",
    "nameEn": "Sierra Leone",
    "calling": "232"
  },
  {
    "iso": "SC",
    "name": "سيشل",
    "nameEn": "Seychelles",
    "calling": "248"
  },
  {
    "iso": "RS",
    "name": "صربيا",
    "nameEn": "Serbia",
    "calling": "381"
  },
  {
    "iso": "TJ",
    "name": "طاجيكستان",
    "nameEn": "Tajikistan",
    "calling": "992"
  },
  {
    "iso": "OM",
    "name": "عُمان",
    "nameEn": "Oman",
    "calling": "968"
  },
  {
    "iso": "GM",
    "name": "غامبيا",
    "nameEn": "Gambia",
    "calling": "220"
  },
  {
    "iso": "GH",
    "name": "غانا",
    "nameEn": "Ghana",
    "calling": "233"
  },
  {
    "iso": "GD",
    "name": "غرينادا",
    "nameEn": "Grenada",
    "calling": "1"
  },
  {
    "iso": "GL",
    "name": "غرينلاند",
    "nameEn": "Greenland",
    "calling": "299"
  },
  {
    "iso": "GT",
    "name": "غواتيمالا",
    "nameEn": "Guatemala",
    "calling": "502"
  },
  {
    "iso": "GP",
    "name": "غوادلوب",
    "nameEn": "Guadeloupe",
    "calling": "590"
  },
  {
    "iso": "GU",
    "name": "غوام",
    "nameEn": "Guam",
    "calling": "1"
  },
  {
    "iso": "GF",
    "name": "غويانا الفرنسية",
    "nameEn": "French Guiana",
    "calling": "594"
  },
  {
    "iso": "GY",
    "name": "غيانا",
    "nameEn": "Guyana",
    "calling": "592"
  },
  {
    "iso": "GG",
    "name": "غيرنزي",
    "nameEn": "Guernsey",
    "calling": "44"
  },
  {
    "iso": "GN",
    "name": "غينيا",
    "nameEn": "Guinea",
    "calling": "224"
  },
  {
    "iso": "GQ",
    "name": "غينيا الاستوائية",
    "nameEn": "Equatorial Guinea",
    "calling": "240"
  },
  {
    "iso": "GW",
    "name": "غينيا بيساو",
    "nameEn": "Guinea-Bissau",
    "calling": "245"
  },
  {
    "iso": "VU",
    "name": "فانواتو",
    "nameEn": "Vanuatu",
    "calling": "678"
  },
  {
    "iso": "FR",
    "name": "فرنسا",
    "nameEn": "France",
    "calling": "33"
  },
  {
    "iso": "VE",
    "name": "فنزويلا",
    "nameEn": "Venezuela",
    "calling": "58"
  },
  {
    "iso": "FI",
    "name": "فنلندا",
    "nameEn": "Finland",
    "calling": "358"
  },
  {
    "iso": "VN",
    "name": "فيتنام",
    "nameEn": "Vietnam",
    "calling": "84"
  },
  {
    "iso": "FJ",
    "name": "فيجي",
    "nameEn": "Fiji",
    "calling": "679"
  },
  {
    "iso": "CY",
    "name": "قبرص",
    "nameEn": "Cyprus",
    "calling": "357"
  },
  {
    "iso": "QA",
    "name": "قطر",
    "nameEn": "Qatar",
    "calling": "974"
  },
  {
    "iso": "KG",
    "name": "قيرغيزستان",
    "nameEn": "Kyrgyzstan",
    "calling": "996"
  },
  {
    "iso": "KZ",
    "name": "كازاخستان",
    "nameEn": "Kazakhstan",
    "calling": "7"
  },
  {
    "iso": "NC",
    "name": "كاليدونيا الجديدة",
    "nameEn": "New Caledonia",
    "calling": "687"
  },
  {
    "iso": "HR",
    "name": "كرواتيا",
    "nameEn": "Croatia",
    "calling": "385"
  },
  {
    "iso": "KH",
    "name": "كمبوديا",
    "nameEn": "Cambodia",
    "calling": "855"
  },
  {
    "iso": "CA",
    "name": "كندا",
    "nameEn": "Canada",
    "calling": "1"
  },
  {
    "iso": "CU",
    "name": "كوبا",
    "nameEn": "Cuba",
    "calling": "53"
  },
  {
    "iso": "CW",
    "name": "كوراساو",
    "nameEn": "Curaçao",
    "calling": "599"
  },
  {
    "iso": "KR",
    "name": "كوريا الجنوبية",
    "nameEn": "South Korea",
    "calling": "82"
  },
  {
    "iso": "KP",
    "name": "كوريا الشمالية",
    "nameEn": "North Korea",
    "calling": "850"
  },
  {
    "iso": "CR",
    "name": "كوستاريكا",
    "nameEn": "Costa Rica",
    "calling": "506"
  },
  {
    "iso": "XK",
    "name": "كوسوفو",
    "nameEn": "Kosovo",
    "calling": "383"
  },
  {
    "iso": "CO",
    "name": "كولومبيا",
    "nameEn": "Colombia",
    "calling": "57"
  },
  {
    "iso": "KI",
    "name": "كيريباتي",
    "nameEn": "Kiribati",
    "calling": "686"
  },
  {
    "iso": "KE",
    "name": "كينيا",
    "nameEn": "Kenya",
    "calling": "254"
  },
  {
    "iso": "LV",
    "name": "لاتفيا",
    "nameEn": "Latvia",
    "calling": "371"
  },
  {
    "iso": "LA",
    "name": "لاوس",
    "nameEn": "Laos",
    "calling": "856"
  },
  {
    "iso": "LB",
    "name": "لبنان",
    "nameEn": "Lebanon",
    "calling": "961"
  },
  {
    "iso": "LU",
    "name": "لوكسمبورغ",
    "nameEn": "Luxembourg",
    "calling": "352"
  },
  {
    "iso": "LY",
    "name": "ليبيا",
    "nameEn": "Libya",
    "calling": "218"
  },
  {
    "iso": "LR",
    "name": "ليبيريا",
    "nameEn": "Liberia",
    "calling": "231"
  },
  {
    "iso": "LT",
    "name": "ليتوانيا",
    "nameEn": "Lithuania",
    "calling": "370"
  },
  {
    "iso": "LI",
    "name": "ليختنشتاين",
    "nameEn": "Liechtenstein",
    "calling": "423"
  },
  {
    "iso": "LS",
    "name": "ليسوتو",
    "nameEn": "Lesotho",
    "calling": "266"
  },
  {
    "iso": "MT",
    "name": "مالطا",
    "nameEn": "Malta",
    "calling": "356"
  },
  {
    "iso": "ML",
    "name": "مالي",
    "nameEn": "Mali",
    "calling": "223"
  },
  {
    "iso": "MY",
    "name": "ماليزيا",
    "nameEn": "Malaysia",
    "calling": "60"
  },
  {
    "iso": "YT",
    "name": "مايوت",
    "nameEn": "Mayotte",
    "calling": "262"
  },
  {
    "iso": "MG",
    "name": "مدغشقر",
    "nameEn": "Madagascar",
    "calling": "261"
  },
  {
    "iso": "EG",
    "name": "مصر",
    "nameEn": "Egypt",
    "calling": "20"
  },
  {
    "iso": "MK",
    "name": "مقدونيا الشمالية",
    "nameEn": "North Macedonia",
    "calling": "389"
  },
  {
    "iso": "MW",
    "name": "ملاوي",
    "nameEn": "Malawi",
    "calling": "265"
  },
  {
    "iso": "MO",
    "name": "منطقة ماكاو الإدارية الخاصة",
    "nameEn": "Macao SAR China",
    "calling": "853"
  },
  {
    "iso": "MN",
    "name": "منغوليا",
    "nameEn": "Mongolia",
    "calling": "976"
  },
  {
    "iso": "MR",
    "name": "موريتانيا",
    "nameEn": "Mauritania",
    "calling": "222"
  },
  {
    "iso": "MU",
    "name": "موريشيوس",
    "nameEn": "Mauritius",
    "calling": "230"
  },
  {
    "iso": "MZ",
    "name": "موزمبيق",
    "nameEn": "Mozambique",
    "calling": "258"
  },
  {
    "iso": "MD",
    "name": "مولدوفا",
    "nameEn": "Moldova",
    "calling": "373"
  },
  {
    "iso": "MC",
    "name": "موناكو",
    "nameEn": "Monaco",
    "calling": "377"
  },
  {
    "iso": "MS",
    "name": "مونتسرات",
    "nameEn": "Montserrat",
    "calling": "1"
  },
  {
    "iso": "MM",
    "name": "ميانمار (بورما)",
    "nameEn": "Myanmar (Burma)",
    "calling": "95"
  },
  {
    "iso": "FM",
    "name": "ميكرونيزيا",
    "nameEn": "Micronesia",
    "calling": "691"
  },
  {
    "iso": "NA",
    "name": "ناميبيا",
    "nameEn": "Namibia",
    "calling": "264"
  },
  {
    "iso": "NR",
    "name": "ناورو",
    "nameEn": "Nauru",
    "calling": "674"
  },
  {
    "iso": "NP",
    "name": "نيبال",
    "nameEn": "Nepal",
    "calling": "977"
  },
  {
    "iso": "NG",
    "name": "نيجيريا",
    "nameEn": "Nigeria",
    "calling": "234"
  },
  {
    "iso": "NI",
    "name": "نيكاراغوا",
    "nameEn": "Nicaragua",
    "calling": "505"
  },
  {
    "iso": "NZ",
    "name": "نيوزيلندا",
    "nameEn": "New Zealand",
    "calling": "64"
  },
  {
    "iso": "NU",
    "name": "نيوي",
    "nameEn": "Niue",
    "calling": "683"
  },
  {
    "iso": "HT",
    "name": "هايتي",
    "nameEn": "Haiti",
    "calling": "509"
  },
  {
    "iso": "HN",
    "name": "هندوراس",
    "nameEn": "Honduras",
    "calling": "504"
  },
  {
    "iso": "HU",
    "name": "هنغاريا",
    "nameEn": "Hungary",
    "calling": "36"
  },
  {
    "iso": "NL",
    "name": "هولندا",
    "nameEn": "Netherlands",
    "calling": "31"
  },
  {
    "iso": "BQ",
    "name": "هولندا الكاريبية",
    "nameEn": "Caribbean Netherlands",
    "calling": "599"
  },
  {
    "iso": "HK",
    "name": "هونغ كونغ الصينية (منطقة إدارية خاصة)",
    "nameEn": "Hong Kong SAR China",
    "calling": "852"
  }
];
