-- WC2026 PRODUCTION SCHEDULE (104 official fixtures). Generated.
-- Run in Supabase SQL Editor. Idempotent: re-running re-syncs schedule
-- metadata (stage/teams/kickoff/venue) WITHOUT touching entered results.
BEGIN;

-- ===== PRE-LAUNCH TEST CLEANUP — REMOVE THIS BLOCK BEFORE ANY PRODUCTION RE-RUN =====
DELETE FROM "Prediction";
DELETE FROM "PredictionAuditLog";
DELETE FROM "MatchResultAuditLog";
DELETE FROM "LeaderboardEntry";
DELETE FROM "User" WHERE "employeeId" LIKE 'e2e_%';
UPDATE "Match" SET "status"='SCHEDULED', "homeScore"=NULL, "awayScore"=NULL, "winnerTeamId"=NULL, "resultConfirmedAt"=NULL, "wentToPenalties"=false;
DELETE FROM "Match" WHERE "matchNumber" NOT BETWEEN 1 AND 104;
-- ===== END PRE-LAUNCH CLEANUP =====

-- Upsert the 104 fixtures (DO UPDATE only re-syncs schedule fields).
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_1', 1, 'GROUP'::"Stage", 'team_mex', 'team_rsa', '2026-06-11 19:00:00', 'Mexico City', 'Mexico City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_2', 2, 'GROUP'::"Stage", 'team_kor', 'team_cze', '2026-06-12 02:00:00', 'Guadalajara', 'Estadio Guadalajara', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_3', 3, 'GROUP'::"Stage", 'team_can', 'team_bih', '2026-06-12 19:00:00', 'Toronto', 'Toronto Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_4', 4, 'GROUP'::"Stage", 'team_usa', 'team_par', '2026-06-13 01:00:00', 'Los Angeles', 'Los Angeles Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_5', 5, 'GROUP'::"Stage", 'team_qat', 'team_sui', '2026-06-13 19:00:00', 'San Francisco Bay Area', 'San Francisco Bay Area Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_6', 6, 'GROUP'::"Stage", 'team_bra', 'team_mar', '2026-06-13 22:00:00', 'New York / New Jersey', 'New York New Jersey Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_7', 7, 'GROUP'::"Stage", 'team_hai', 'team_sco', '2026-06-14 01:00:00', 'Boston', 'Boston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_8', 8, 'GROUP'::"Stage", 'team_aus', 'team_tur', '2026-06-14 04:00:00', 'Vancouver', 'BC Place Vancouver', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_9', 9, 'GROUP'::"Stage", 'team_ger', 'team_cuw', '2026-06-14 17:00:00', 'Houston', 'Houston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_10', 10, 'GROUP'::"Stage", 'team_ned', 'team_jpn', '2026-06-14 20:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_11', 11, 'GROUP'::"Stage", 'team_civ', 'team_ecu', '2026-06-14 23:00:00', 'Philadelphia', 'Philadelphia Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_12', 12, 'GROUP'::"Stage", 'team_swe', 'team_tun', '2026-06-15 02:00:00', 'Monterrey', 'Estadio Monterrey', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_13', 13, 'GROUP'::"Stage", 'team_esp', 'team_cpv', '2026-06-15 16:00:00', 'Atlanta', 'Atlanta Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_14', 14, 'GROUP'::"Stage", 'team_bel', 'team_egy', '2026-06-15 19:00:00', 'Seattle', 'Seattle Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_15', 15, 'GROUP'::"Stage", 'team_ksa', 'team_uru', '2026-06-15 22:00:00', 'Miami', 'Miami Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_16', 16, 'GROUP'::"Stage", 'team_irn', 'team_nzl', '2026-06-16 01:00:00', 'Los Angeles', 'Los Angeles Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_17', 17, 'GROUP'::"Stage", 'team_fra', 'team_sen', '2026-06-16 19:00:00', 'New York / New Jersey', 'New York New Jersey Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_18', 18, 'GROUP'::"Stage", 'team_irq', 'team_nor', '2026-06-16 22:00:00', 'Boston', 'Boston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_19', 19, 'GROUP'::"Stage", 'team_arg', 'team_alg', '2026-06-17 01:00:00', 'Kansas City', 'Kansas City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_20', 20, 'GROUP'::"Stage", 'team_aut', 'team_jor', '2026-06-17 04:00:00', 'San Francisco Bay Area', 'San Francisco Bay Area Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_21', 21, 'GROUP'::"Stage", 'team_por', 'team_cod', '2026-06-17 17:00:00', 'Houston', 'Houston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_22', 22, 'GROUP'::"Stage", 'team_eng', 'team_cro', '2026-06-17 20:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_23', 23, 'GROUP'::"Stage", 'team_gha', 'team_pan', '2026-06-17 23:00:00', 'Toronto', 'Toronto Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_24', 24, 'GROUP'::"Stage", 'team_uzb', 'team_col', '2026-06-18 02:00:00', 'Mexico City', 'Mexico City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_25', 25, 'GROUP'::"Stage", 'team_cze', 'team_rsa', '2026-06-18 16:00:00', 'Atlanta', 'Atlanta Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_26', 26, 'GROUP'::"Stage", 'team_sui', 'team_bih', '2026-06-18 19:00:00', 'Los Angeles', 'Los Angeles Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_27', 27, 'GROUP'::"Stage", 'team_can', 'team_qat', '2026-06-18 22:00:00', 'Vancouver', 'BC Place Vancouver', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_28', 28, 'GROUP'::"Stage", 'team_mex', 'team_kor', '2026-06-19 01:00:00', 'Guadalajara', 'Estadio Guadalajara', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_29', 29, 'GROUP'::"Stage", 'team_usa', 'team_aus', '2026-06-19 19:00:00', 'Seattle', 'Seattle Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_30', 30, 'GROUP'::"Stage", 'team_sco', 'team_mar', '2026-06-19 22:00:00', 'Boston', 'Boston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_31', 31, 'GROUP'::"Stage", 'team_bra', 'team_hai', '2026-06-20 00:30:00', 'Philadelphia', 'Philadelphia Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_32', 32, 'GROUP'::"Stage", 'team_tur', 'team_par', '2026-06-20 03:00:00', 'San Francisco Bay Area', 'San Francisco Bay Area Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_33', 33, 'GROUP'::"Stage", 'team_ned', 'team_swe', '2026-06-20 17:00:00', 'Houston', 'Houston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_34', 34, 'GROUP'::"Stage", 'team_ger', 'team_civ', '2026-06-20 20:00:00', 'Toronto', 'Toronto Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_35', 35, 'GROUP'::"Stage", 'team_ecu', 'team_cuw', '2026-06-21 00:00:00', 'Kansas City', 'Kansas City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_36', 36, 'GROUP'::"Stage", 'team_tun', 'team_jpn', '2026-06-21 04:00:00', 'Monterrey', 'Estadio Monterrey', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_37', 37, 'GROUP'::"Stage", 'team_esp', 'team_ksa', '2026-06-21 16:00:00', 'Atlanta', 'Atlanta Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_38', 38, 'GROUP'::"Stage", 'team_bel', 'team_irn', '2026-06-21 19:00:00', 'Los Angeles', 'Los Angeles Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_39', 39, 'GROUP'::"Stage", 'team_uru', 'team_cpv', '2026-06-21 22:00:00', 'Miami', 'Miami Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_40', 40, 'GROUP'::"Stage", 'team_nzl', 'team_egy', '2026-06-22 01:00:00', 'Vancouver', 'BC Place Vancouver', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_41', 41, 'GROUP'::"Stage", 'team_arg', 'team_aut', '2026-06-22 17:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_42', 42, 'GROUP'::"Stage", 'team_fra', 'team_irq', '2026-06-22 21:00:00', 'Philadelphia', 'Philadelphia Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_43', 43, 'GROUP'::"Stage", 'team_nor', 'team_sen', '2026-06-23 00:00:00', 'Toronto', 'Toronto Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_44', 44, 'GROUP'::"Stage", 'team_jor', 'team_alg', '2026-06-23 03:00:00', 'San Francisco Bay Area', 'San Francisco Bay Area Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_45', 45, 'GROUP'::"Stage", 'team_por', 'team_uzb', '2026-06-23 17:00:00', 'Houston', 'Houston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_46', 46, 'GROUP'::"Stage", 'team_eng', 'team_gha', '2026-06-23 20:00:00', 'Boston', 'Boston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_47', 47, 'GROUP'::"Stage", 'team_pan', 'team_cro', '2026-06-23 23:00:00', 'Boston', 'Boston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_48', 48, 'GROUP'::"Stage", 'team_col', 'team_cod', '2026-06-24 02:00:00', 'Guadalajara', 'Estadio Guadalajara', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_49', 49, 'GROUP'::"Stage", 'team_sui', 'team_can', '2026-06-24 19:00:00', 'Vancouver', 'BC Place Vancouver', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_50', 50, 'GROUP'::"Stage", 'team_bih', 'team_qat', '2026-06-24 19:00:00', 'Seattle', 'Seattle Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_51', 51, 'GROUP'::"Stage", 'team_mar', 'team_hai', '2026-06-24 22:00:00', 'Atlanta', 'Atlanta Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_52', 52, 'GROUP'::"Stage", 'team_sco', 'team_bra', '2026-06-24 22:00:00', 'Miami', 'Miami Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_53', 53, 'GROUP'::"Stage", 'team_rsa', 'team_kor', '2026-06-25 01:00:00', 'Monterrey', 'Estadio Monterrey', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_54', 54, 'GROUP'::"Stage", 'team_cze', 'team_mex', '2026-06-25 01:00:00', 'Mexico City', 'Mexico City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_55', 55, 'GROUP'::"Stage", 'team_cuw', 'team_civ', '2026-06-25 20:00:00', 'Philadelphia', 'Philadelphia Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_56', 56, 'GROUP'::"Stage", 'team_ecu', 'team_ger', '2026-06-25 20:00:00', 'New York / New Jersey', 'New York New Jersey Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_57', 57, 'GROUP'::"Stage", 'team_tun', 'team_ned', '2026-06-25 23:00:00', 'Kansas City', 'Kansas City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_58', 58, 'GROUP'::"Stage", 'team_jpn', 'team_swe', '2026-06-25 23:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_59', 59, 'GROUP'::"Stage", 'team_tur', 'team_usa', '2026-06-26 02:00:00', 'Los Angeles', 'Los Angeles Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_60', 60, 'GROUP'::"Stage", 'team_par', 'team_aus', '2026-06-26 02:00:00', 'San Francisco Bay Area', 'San Francisco Bay Area Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_61', 61, 'GROUP'::"Stage", 'team_nor', 'team_fra', '2026-06-26 19:00:00', 'Boston', 'Boston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_62', 62, 'GROUP'::"Stage", 'team_sen', 'team_irq', '2026-06-26 19:00:00', 'Toronto', 'Toronto Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_63', 63, 'GROUP'::"Stage", 'team_cpv', 'team_ksa', '2026-06-27 00:00:00', 'Houston', 'Houston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_64', 64, 'GROUP'::"Stage", 'team_uru', 'team_esp', '2026-06-27 00:00:00', 'Guadalajara', 'Estadio Guadalajara', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_65', 65, 'GROUP'::"Stage", 'team_nzl', 'team_bel', '2026-06-27 03:00:00', 'Vancouver', 'BC Place Vancouver', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_66', 66, 'GROUP'::"Stage", 'team_egy', 'team_irn', '2026-06-27 03:00:00', 'Seattle', 'Seattle Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_67', 67, 'GROUP'::"Stage", 'team_pan', 'team_eng', '2026-06-27 21:00:00', 'New York / New Jersey', 'New York New Jersey Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_68', 68, 'GROUP'::"Stage", 'team_cro', 'team_gha', '2026-06-27 21:00:00', 'Philadelphia', 'Philadelphia Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_69', 69, 'GROUP'::"Stage", 'team_col', 'team_por', '2026-06-27 23:30:00', 'Miami', 'Miami Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_70', 70, 'GROUP'::"Stage", 'team_cod', 'team_uzb', '2026-06-27 23:30:00', 'Atlanta', 'Atlanta Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_71', 71, 'GROUP'::"Stage", 'team_alg', 'team_aut', '2026-06-28 02:00:00', 'Kansas City', 'Kansas City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_72', 72, 'GROUP'::"Stage", 'team_jor', 'team_arg', '2026-06-28 02:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_73', 73, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-06-28 19:00:00', 'Los Angeles', 'Los Angeles Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_74', 74, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-06-29 17:00:00', 'Houston', 'Houston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_75', 75, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-06-29 20:30:00', 'Boston', 'Boston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_76', 76, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-06-30 01:00:00', 'Monterrey', 'Estadio Monterrey', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_77', 77, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-06-30 17:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_78', 78, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-06-30 21:00:00', 'New York / New Jersey', 'New York New Jersey Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_79', 79, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-01 01:00:00', 'Mexico City', 'Mexico City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_80', 80, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-01 16:00:00', 'Atlanta', 'Atlanta Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_81', 81, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-01 20:00:00', 'Seattle', 'Seattle Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_82', 82, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-02 00:00:00', 'San Francisco Bay Area', 'San Francisco Bay Area Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_83', 83, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-02 19:00:00', 'Los Angeles', 'Los Angeles Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_84', 84, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-02 23:00:00', 'Toronto', 'Toronto Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_85', 85, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-03 03:00:00', 'Vancouver', 'BC Place Vancouver', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_86', 86, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-03 18:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_87', 87, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-03 22:00:00', 'Miami', 'Miami Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_88', 88, 'ROUND_OF_32'::"Stage", NULL, NULL, '2026-07-04 01:30:00', 'Kansas City', 'Kansas City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_89', 89, 'ROUND_OF_16'::"Stage", NULL, NULL, '2026-07-04 17:00:00', 'Houston', 'Houston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_90', 90, 'ROUND_OF_16'::"Stage", NULL, NULL, '2026-07-04 21:00:00', 'Philadelphia', 'Philadelphia Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_91', 91, 'ROUND_OF_16'::"Stage", NULL, NULL, '2026-07-05 20:00:00', 'New York / New Jersey', 'New York New Jersey Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_92', 92, 'ROUND_OF_16'::"Stage", NULL, NULL, '2026-07-06 00:00:00', 'Mexico City', 'Mexico City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_93', 93, 'ROUND_OF_16'::"Stage", NULL, NULL, '2026-07-06 19:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_94', 94, 'ROUND_OF_16'::"Stage", NULL, NULL, '2026-07-07 00:00:00', 'Seattle', 'Seattle Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_95', 95, 'ROUND_OF_16'::"Stage", NULL, NULL, '2026-07-07 16:00:00', 'Atlanta', 'Atlanta Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_96', 96, 'ROUND_OF_16'::"Stage", NULL, NULL, '2026-07-07 20:00:00', 'Vancouver', 'BC Place Vancouver', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_97', 97, 'QUARTER_FINAL'::"Stage", NULL, NULL, '2026-07-09 20:00:00', 'Boston', 'Boston Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_98', 98, 'QUARTER_FINAL'::"Stage", NULL, NULL, '2026-07-10 19:00:00', 'Los Angeles', 'Los Angeles Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_99', 99, 'QUARTER_FINAL'::"Stage", NULL, NULL, '2026-07-11 21:00:00', 'Miami', 'Miami Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_100', 100, 'QUARTER_FINAL'::"Stage", NULL, NULL, '2026-07-12 01:00:00', 'Kansas City', 'Kansas City Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_101', 101, 'SEMI_FINAL'::"Stage", NULL, NULL, '2026-07-14 19:00:00', 'Dallas', 'Dallas Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_102', 102, 'SEMI_FINAL'::"Stage", NULL, NULL, '2026-07-15 19:00:00', 'Atlanta', 'Atlanta Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_103', 103, 'THIRD_PLACE'::"Stage", NULL, NULL, '2026-07-18 21:00:00', 'Miami', 'Miami Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();
INSERT INTO "Match" ("id","matchNumber","stage","homeTeamId","awayTeamId","kickoffAt","city","stadium","status","wentToPenalties","createdAt","updatedAt") VALUES ('mtch_104', 104, 'FINAL'::"Stage", NULL, NULL, '2026-07-19 19:00:00', 'New York / New Jersey', 'New York New Jersey Stadium', 'SCHEDULED', false, now(), now()) ON CONFLICT ("matchNumber") DO UPDATE SET "stage"=EXCLUDED."stage", "homeTeamId"=EXCLUDED."homeTeamId", "awayTeamId"=EXCLUDED."awayTeamId", "kickoffAt"=EXCLUDED."kickoffAt", "city"=EXCLUDED."city", "stadium"=EXCLUDED."stadium", "updatedAt"=now();

-- Grant ADMIN to employee 302254 (no-op if not yet registered).
-- For first-login auto-promotion also add 302254 to ADMIN_EMPLOYEE_IDS in Vercel.
UPDATE "User" SET "role"='ADMIN' WHERE "employeeId"='302254';

COMMIT;
